fos_rest:
    param_fetcher_listener: true
    #    allowed_methods_listener:  true
    # default_format: json
    # include_format: false
    body_listener: true
  ##  view:
    ##    view_response_listener: "force"
      ##  formats:
        ##    json: true
    #    exception:
    #        codes:
    #            App\Exception\MyException: 403
    #        messages:
    #            App\Exception\MyException: Forbidden area.
    ##format_listener:
      ##  rules:
        ##    - {
          ##        path: ^/,
            ##      priorities: [json],
              ##    prefer_extension: false,
               ##   fallback_format: json,
             ## }